# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osbb.Apartment'),
        ),
    ]
