# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0004_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='meter',
            new_name='apartment',
        ),
    ]
