# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0005_auto_20170717_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='apartment',
        ),
        migrations.AddField(
            model_name='person',
            name='apartments',
            field=models.ManyToManyField(related_name='persons', to='osbb.Apartment'),
        ),
    ]
