# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0008_auto_20170719_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personal_account', serialize=False, to='osbb.Apartment'),
        ),
        migrations.AlterField(
            model_name='service',
            name='personal_accounts',
            field=models.ManyToManyField(related_name='services', to='osbb.PersonalAccount'),
        ),
    ]
