# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0009_auto_20170719_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgaccount',
            name='number',
        ),
        migrations.AddField(
            model_name='orgaccount',
            name='requisites_text',
            field=models.TextField(default=''),
        ),
    ]
