# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osbb', '0011_auto_20170719_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orgbalance',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
